// Global UI Action
export const TOGGLE_SIDEBAR = 'TOGGLE_SIDEBAR';
export const OPEN_SUBMENU = 'OPEN_SUBMENU';
export const CLOSE_ALL_SUBMENU = 'CLOSE_ALL_SUBMENU';
export const CHANGE_THEME = 'CHANGE_THEME';
export const CHANGE_MODE = 'CHANGE_MODE';
export const CHANGE_GRADIENT = 'CHANGE_GRADIENT';
export const CHANGE_DECO = 'CHANGE_DECO';
export const CHANGE_BG_POSITION = 'CHANGE_BG_POSITION';
export const CHANGE_LAYOUT = 'CHANGE_LAYOUT';
export const LOAD_PAGE = 'LOAD_PAGE';
// Redux Form
export const INIT = 'INIT';
export const CLEAR = 'CLEAR';
// Flows
export const GET_FLOWS = 'GET_FLOWS';

// Orders
export const GET_ORDERS = 'GET_ORDERS';
export const GET_ORDERS_START = 'GET_ORDERS_START';
export const GET_ORDERS_SUCCESS = 'GET_ORDERS_SUCCESS';
export const GET_ORDERS_FAILED = 'GET_ORDERS_FAILED';

// Integrations
export const GET_INTEGRATIONS = 'GET_INTEGRATIONS';
export const GET_INTEGRATIONS_START = 'GET_INTEGRATIONS_START';
export const GET_INTEGRATIONS_SUCCESS = 'GET_INTEGRATIONS_SUCCESS';
export const GET_INTEGRATIONS_FAILED = 'GET_INTEGRATIONS_FAILED';

export const AUTH_LOGOUT = 'AUTH_LOGOUT';

export const GET_TENANT = 'GET_TENANT';
export const SET_TENANT_STATUS = 'SET_TENANT_STATUS';
export const GET_TENANT_LIST = 'GET_TENANT_LIST';
export const SET_TENANT_LIST = 'SET_TENANT_LIST';
export const GET_RELOAD_TENANTS = 'GET_RELOAD_TENANTS';
export const SET_RELOAD_TENANTS = 'SET_RELOAD_TENANTS';
export const GET_RELOAD_LANDING_PAGE = 'GET_RELOAD_LANDING_PAGE';
export const SET_RELOAD_LANDING_PAGE = 'SET_RELOAD_LANDING_PAGE';
export const GET_PRODUCT_VARIANTS = 'GET_PRODUCT_VARIANTS';
export const SET_PRODUCT_VARIANTS = 'SET_PRODUCT_VARIANTS';
export const GET_PRODUCT_PROPERTIES = 'GET_PRODUCT_PROPERTIES';
export const SET_PRODUCT_PROPERTIES = 'SET_PRODUCT_PROPERTIES';
export const SET_PRODUCT_NAME = 'SET_PRODUCT_NAME';
export const SET_PRODUCT_DESCRIPTION = 'SET_PRODUCT_DESCRIPTION';
export const SET_PRODUCT_PRICE = 'SET_PRODUCT_PRICE';
export const SET_PRODUCT_INTEGRATIONS = 'SET_PRODUCT_INTEGRATIONS';
export const SET_DEACTIVATION_DATE = 'SET_DEACTIVATION_DATE';
export const SET_ENABLED_TENANT = 'SET_ENABLED_TENANT';
export const SET_TENANT_NAME = 'SET_TENANT_NAME';
export const SET_PRODUCT = 'SET_PRODUCT';

export const GET_TENANT_ID = 'GET_TENANT_ID';
export const SET_TENANT_ID = 'SET_TENANT_ID';
