import {
  Tasks,
  TaskDetails,
  Orders,
  OrderDetails,
  Products,
  EditProduct,
  AddProduct,
  AvailableIntegrations,
  Channels,
  InstalledIntegrations,
  AddIntegrationForm,
  Workflows,
  AddWorkflow,
  EditWorkflow,
  Webhooks,
  AddWebhook,
  EditWebhook,
  DashboardPage,
  TenantConfiguration,
  AddTenant,
  InstallShopify
} from '../pageListAsync';

export default [
  { link: '/dashboard', component: DashboardPage },
  { link: '/orders', component: Orders },
  { link: '/orders/:number', component: OrderDetails },
  { link: '/tasks', component: Tasks },
  { link: '/tasks/:id', component: TaskDetails },
  { link: '/products', component: Products },
  { link: '/products/add-product', component: AddProduct },
  { link: '/products/:id', component: EditProduct },
  { link: '/available-integrations', component: AvailableIntegrations },
  { link: '/channels', component: Channels },
  { link: '/installed-integrations', component: InstalledIntegrations },
  { link: '/integrations/add-integration', component: AddIntegrationForm },
  { link: '/workflows', component: Workflows },
  { link: '/workflows/add-workflow', component: AddWorkflow },
  { link: '/workflows/:id', component: EditWorkflow },
  { link: '/add-tenant', component: AddTenant },
  { link: '/webhooks', component: Webhooks },
  { link: '/webhooks/add-webhook', component: AddWebhook },
  { link: '/webhooks/:id', component: EditWebhook },
  { link: '/shopify', component: InstallShopify },
  { link: '/', component: DashboardPage },
  { link: '/tenant-configuration', component: TenantConfiguration }
];
